Fix tests and update README.md
Fix tests

Further fixes

Fix tests

Fix s3:promote description

Attach as s3.amazonaws.com

Revert "Attach as s3.amazonaws.com"

This reverts commit fb777ad6cb088e5a4b43e251b9a46c10aea35df3.

Change docker image to avoid md5 problem with cli

Fix docker image

Use s3rver instead of fakes3

Add bucket commands and tests

Update README.md

Fixes

Fix used docker image

Fix subcommand permissions

Fixes

Fixes

Fixes

Fixes

Fixes

Fixes

Fixes

Fixes

Update README.md

diff --git a/tests/bin/docker b/tests/bin/docker
--- a/tests/bin/docker
+++ b/tests/bin/docker
@@ -40,9 +40,30 @@ case "$1" in
       echo "5e50a462661e        rabbitmq:3.5.4-management  \"/docker-entrypoint.   11 seconds ago       Up 10 seconds       5672/tcp, 15672/tcp              dokku.rabbitmq.l"
       echo "c39ca00fa3c6        redis:3.0.3                \"/entrypoint.sh redi   11 seconds ago       Up 10 seconds       6379/tcp                         dokku.redis.l"
       echo "dc98c2939a80        rethinkdb:2.1.1            \"rethinkdb --bind al   11 seconds ago       Up 10 seconds       8080/tcp, 28015/tcp, 29015/tcp   dokku.rethinkdb.l"
+      echo "41bb4b16554f        seayou/s3rver:latest       \"tini -- s3rver --ho   19 seconds ago       Up 17 seconds       5000/tcp                         dokku.s3.l"
     fi
     ;;
   exec)
+    if [[ $@ = *"s3 ls --output text | cut -c21- | egrep ^lll$"* ]]; then
+      echo "lll"
+      exit 0
+    fi
+
+    if [[ $@ = *"s3 ls --output text | cut -c21- | egrep ^mmm$"* ]]; then
+      echo ""
+      exit 0
+    fi
+
+    if [[ $@ = *"s3 ls --output text | cut -c21- | egrep ^l$"* ]]; then
+      echo ""
+      exit 0
+    fi
+
+    if [[ $@ = *"s3 mb s3://l --output text"* ]]; then
+      echo "s3rver failed to create bucket: l"
+      exit 1
+    fi
+
     echo "exec called with $@"
     ;;
   inspect)
@@ -80,6 +101,7 @@ case "$1" in
     echo "redis                     3.0.3               9216d5a4eec8        13 days ago         109.3 MB"
     echo "rethinkdb                 2.1.1               f27010a550ec        13 days ago         196.3 MB"
     echo "svendowideit/ambassador   latest              0d2200edc53e        21 months ago       7.241 MB"
+    echo "seayou/s3rver             latest              fc3c84ce2bf3        9 weeks ago         45.86 MB"
     ;;
   pull)
     exit 0
